[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  HUGO_VERSION = "0.129.0"

[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"

[context.next]
  command = "pnpm build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
## Gitpod
[[redirects]]
  from = "/basics"
  to = "https://gitpod.io/#https://github.com/gethyas/basic-starter"
  status = 301
  force = true
  query = {on = "gitpod"}

[[redirects]]
  from = "/bolt"
  to = "https://gitpod.io/#https://github.com/gethyas/bolt"
  status = 301
  force = true
  query = {on = "gitpod"}

[[redirects]]
  from = "/bootstrap"
  to = "https://gitpod.io/#https://github.com/gethyas/bootstrap-starter"
  status = 301
  force = true
  query = {on = "gitpod"}

[[redirects]]
  from = "/doks"
  to = "https://gitpod.io/#https://github.com/gethyas/doks"
  status = 301
  force = true
  query = {on = "gitpod"}

[[redirects]]
  from = "/talwind-css"
  to = "https://gitpod.io/#https://github.com/gethyas/tailwindcss-starter"
  status = 301
  force = true
  query = {on = "gitpod"}

## CodeSandbox
[[redirects]]
  from = "/basics"
  to = "https://codesandbox.io/p/sandbox/github/gethyas/basic-starter"
  status = 301
  force = true
  query = {on = "codesandbox"}

[[redirects]]
  from = "/bolt"
  to = "https://codesandbox.io/p/sandbox/github/gethyas/bolt"
  status = 301
  force = true
  query = {on = "codesandbox"}

[[redirects]]
  from = "/bootstrap"
  to = "https://codesandbox.io/p/sandbox/github/gethyas/bootstrap-starter"
  status = 301
  force = true
  query = {on = "codesandbox"}

[[redirects]]
  from = "/doks"
  to = "https://codesandbox.io/p/sandbox/github/gethyas/doks"
  status = 301
  force = true
  query = {on = "codesandbox"}

[[redirects]]
  from = "/talwind-css"
  to = "https://codesandbox.io/p/sandbox/github/gethyas/tailwindcss-starter"
  status = 301
  force = true
  query = {on = "codesandbox"}

## StackBlitz
[[redirects]]
  from = "/basics"
  to = "https://stackblitz.com/github/gethyas/basic-starter"
  status = 301
  force = true
  query = {on = "stackblitz"}

[[redirects]]
  from = "/bolt"
  to = "https://stackblitz.com/github/gethyas/bolt"
  status = 301
  force = true
  query = {on = "stackblitz"}

[[redirects]]
  from = "/bootstrap"
  to = "https://stackblitz.com/github/gethyas/bootstrap-starter"
  status = 301
  force = true
  query = {on = "stackblitz"}

[[redirects]]
  from = "/doks"
  to = "https://stackblitz.com/github/gethyas/doks"
  status = 301
  force = true
  query = {on = "stackblitz"}

[[redirects]]
  from = "/talwind-css"
  to = "https://stackblitz.com/github/gethyas/tailwindcss-starter"
  status = 301
  force = true
  query = {on = "stackblitz"}

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self' https://plausible.io; font-src 'self'; img-src 'self' https://avatars.githubusercontent.com data:; script-src 'self' https://plausible.io 'nonce-dXNlcj0iaGVsbG8iLGRvbWFpbj0iaGVua3ZlcmxpbmRlLmNvbSIsZG9jdW1lbnQud3JpdGUodXNlcisiQCIrZG9tYWluKTs=' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk='; style-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Feature-Policy = "geolocation 'self'"
    Cache-Control= '''
    public,
    max-age=31536000'''
    Access-Control-Allow-Origin = "*"
